name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Каждый день в полночь
  workflow_dispatch:  # Ручной запуск
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          user: lourq
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Kiev

          # Isocalendar (график активности)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Языки программирования
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_colors: github

          # Достижения
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

      - name: Generate languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg
          user: lourq
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_colors: github

      - name: Generate habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits.svg
          user: lourq
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Europe/Kiev
